shield:
  decay-interval: 1
  center:
    x: 0
    z: 0
  side-length: 100
  min-y: 70
  max-y: 200
reactor:
  fuel:
    hopper:
      x: 1
      y: 70
      z: 0
    consumption: 1
    initial: 200
    warning:
      min: 100
      max: 300
    meltdown:
      min: 50
      max: 400
  coolant:
    hopper:
      x: -1
      y: 70
      z: 0
    consumption: 1
    initial: 1000
    warning:
      min: 500
      max: 1500
    meltdown:
      min: 250
      max: 1750

  tnt:
    fill-min:
      x: -50
      y: 65
      z: -50
    fill-max:
      x: 50
      y: 68
      z: 50
    primed:
      x: 0
      y: 68
      z: 0
redstone-spawning:
  interval: 20
  center:
    x: 0
    z: 0
  radius: 50
  min-y: 5
  max-y: 30
